spring:
  application:
    # 服务名称
    name: eureka
server:
  port: 1111
eureka:
  instance:
    hostname: eureka-a
  client:
    # 自己注册到注册中心
    register-with-eureka: true
    # 不从注册中心获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1112/eureka